### ISSUE TITLE
[BUG] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by starlett3** [rapidsai/notebooks#107]
I'm running the notebooks/cuml/linear_regression_demo notebook.
On the line:
`X_cudf = cudf.DataFrame.from_pandas(X_train)`

I get error:
> ERROR:Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

I'm running this on:
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
on a machine with four V100s
Driver Version: 410.104      
CUDA Version: 10.0

**Comment by rpanai** [comment]
I've the same problem.

**Comment by ksangeek** [comment]
I have also been hitting this error reported here -
`numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE` or sometimes this error `

or sometimes this error reported in https://github.com/rapidsai/cudf/issues/1205 -
`numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE`

Looking further it is not specific to this example but looks like something related to the amount of free space in GPU memory. I'll provide more details on how I am able to recreate this consistently -

1. Start a process to load-up a good amount of GPU memory. This code-snippet here can do that -
```
import numpy as np
import pandas as pd
from cuml import PCA as cuPCA
import cudf

nrows=2**21
ncols=800

X = np.random.rand(nrows,ncols)
df = pd.DataFrame({'fea%d'%i:X[:,i] for i in range(X.shape[1])})

print('df shape - ',df.shape)
print('df size - ',df.memory_usage(index=True).sum())

cdf = cudf.DataFrame.from_pandas(df)
```

2. Start this program in `pdb`, so that you can create the `cuDF` and allow it to block a good chunk of GPU memory.
In my case, I go till here and then, keep that session active -
```
> /mnt/pai/home/sangeek/sandbox/cuml-v0.6.1-sk/cuml_mem_test.py(13)<module>()
-> print('df shape - ',df.shape)
(Pdb)
df shape -  (2097152, 800)
> /mnt/pai/home/sangeek/sandbox/cuml-v0.6.1-sk/cuml_mem_test.py(14)<module>()
-> print('df size - ',df.memory_usage(index=True).sum())
(Pdb)
df size -  13421772880
> /mnt/pai/home/sangeek/sandbox/cuml-v0.6.1-sk/cuml_mem_test.py(16)<module>()
-> cdf = cudf.DataFrame.from_pandas(df)
(Pdb)
```

3. With the process in step 2 continuing to hold up GPU memory, I see `nvidia-smi` output shows the size similar to the size of the pandas dataframe (seen in step 2 as `df size`) being reserved in GPU memory

```
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000004:04:00.0 Off |                    0 |
| N/A   32C    P0    52W / 300W |  13213MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

4. Now start a new process of the same program(in a new session of the same host) to use the same GPU. And that fails with -
```
$ python cuml_mem_test.py
df shape -  (2097152, 800)
df size -  13421772880
ERROR:Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "cuml_mem_test.py", line 16, in <module>
    cdf = cudf.DataFrame.from_pandas(df)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 2146, in from_pandas
    df[colk] = Series(vals, nan_as_null=nan_as_null)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/cudf/dataframe/series.py", line 81, in __init__
    dtype=dtype)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/cudf/dataframe/columnops.py", line 258, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/librmm_cffi/wrapper.py", line 241, in to_device
    to.copy_to_device(ary, stream=stream)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 205, in copy_to_device
    _driver.host_to_device(self, ary, sz, stream=stream)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 1809, in host_to_device
    fn(device_pointer(dst), host_pointer(src), size, *varargs)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/sangeek/anaconda3/envs/cuml-36/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE
```

**Comment by ksangeek** [comment]
If I re-run step 4 ( from above ) with a modified example(which I have quoted below), such that I allow the cuDF of 2nd process to be loaded into memory; then it goes ahead with `fit_transform()` of `pca`, but fails with the `numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY` error which is understandable.

Modified example, to use lower sized cuDF
```
$ cat cuml_mem_test2.py
import numpy as np
import pandas as pd
from cuml import PCA as cuPCA
import cudf

#nrows=2**21 #more-rows
nrows=2**18 #less-rows
ncols=800

X = np.random.rand(nrows,ncols)
df = pd.DataFrame({'fea%d'%i:X[:,i] for i in range(X.shape[1])})

print('df shape - ',df.shape)
print('df size - ',df.memory_usage(index=True).sum())

cdf = cudf.DataFrame.from_pandas(df)

cupca = cuPCA(n_components=2)

cupca.fit_transform(X)
```

I think the issue here is that when cuDF was being loaded into GPU memory using `cuMemcpyHtoD` should have reported `CUDA_ERROR_OUT_OF_MEMORY` instead of `CUDA_ERROR_INVALID_VALUE`!

**Comment by harrism** [comment]
I hope and predict that as we improve exception handling in cuDF over the next two releases the error reporting should get more accurate / helpful. Perhaps what is happening here is an out of memory error is not getting propagated up to the Python layer before an attempt is made to cudaMemcpy into a null pointer (because the allocation of that pointer failed due to OOM). cudaMemcpy to a null pointer would not report out of memory, but probably invalid value...

**Comment by randerzander** [comment]
@harrism I'm also hitting this in workflow dev while running large `merge` operations.

Is it a significant effort to get a more meaningful error bubbled up?

**Comment by kkraus14** [comment]
> @harrism I'm also hitting this in workflow dev while running large `merge` operations.
> 
> Is it a significant effort to get a more meaningful error bubbled up?

It's Numba throwing these errors as we're using it in many situations to handle data movement, so it's likely going to take some time as we move away from using Numba to handle these situations.

**Comment by harrism** [comment]
Also RMM still uses CFFI, so no exceptions.
